#!/bin/sh

cat <<EOF

--------------------------------------------------------------------------------
  Oh My Zsh Plugins
--------------------------------------------------------------------------------

Installing Oh My Zsh Plugins...

EOF

# Remove a file indicates that the plugin is installed.
rm -f ~/.oh-my-zsh-plugins-installed

# Install Oh My Zsh Plugins
# echo "zsh-autosuggestions"
# git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# echo "zsh-syntax-highlighting"
# git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# echo "zsh-z"
# git clone https://github.com/agkozak/zsh-z $ZSH_CUSTOM/plugins/zsh-z

# echo "zsh-nvm"
# git clone https://github.com/lukechilds/zsh-nvm ~/.oh-my-zsh/custom/plugins/zsh-nvm

# echo "powerlevel10k/powerlevel10k"
# git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

cat <<EOF

--------------------------------------------------------------------------------
  Installation Complete!
--------------------------------------------------------------------------------

EOF

# Create a file to indicate that the installation has completed
touch ~/.oh-my-zsh-plugins-installed

