#!/bin/bash

DOTFILES_PATH="${HOME}/dotfiles"

# AI Agents
mkdir -p "${HOME}/.claude"
mkdir -p "${HOME}/.gemini"

ln -sfn "${DOTFILES_PATH}/.agents/claude/settings.json" "${HOME}/.claude/settings.json"
ln -sfn "${DOTFILES_PATH}/.agents/claude/CLAUDE.md" "${HOME}/.claude/CLAUDE.md"
ln -sfn "${DOTFILES_PATH}/.agents/gemini/settings.json" "${HOME}/.gemini/settings.json"

# Neovim
ln -sfn "${DOTFILES_PATH}/.config/nvim" "${HOME}/.config/nvim"
