#!/bin/sh

trap _ERROR ERR
trap _FINISH EXIT

INSTALLING_FILE=""
ERROR_COUNT=0

INSTALL() {
  printf "\e[32mInstalling: \e[m$1\n"
  INSTALLING_FILE=$1
}

UNINSTALL() {
  printf "\e[31mUninstalling: \e[m$1\n"
  INSTALLING_FILE=$1
}

_FINISH() {
  if [ $ERROR_COUNT -gt 0 ]; then
    printf "\n\e[1;37;41m $ERROR_COUNT errors \e[m\n\n"
  else
    printf "\n\e[1;37;42m Done \e[m\n\n"
  fi
}

_ERROR() {
  printf "\e[1;37;41m Error \e[m $INSTALLING_FILE\n"
  ERROR_COUNT=$((ERROR_COUNT + 1))
}
