##################################################
# > Alias
##################################################
alias cd="z"
alias ls="ls -p -G"
alias la "ls -A"
alias ll="ls -l"
alias lla="ls -A"
alias g="git"
alias gs="git status"
alias lzg="lazygit"
alias lzd="lazydocker"
alias fzf="fzf --preview 'bat --color=always --style=numbers {}'"
alias posh="pwsh"
alias cls="clear"
alias md="mkdir"
alias e="emacs"
alias ee="emacsclient -nw"
alias emacsd="emacs --daemon"
alias vim="nvim"
alias nf="neofetch"
alias datetime="date '+%Y-%m-%d %H:%H:%S'"
alias sail="[ -f sail ] && sh sail || sh vendor/bin/sail"
alias dep="[ -f dep ] && sh dep || sh vendor/bin/dep"
alias mrm="touch README.md"
alias rb="ruby"
alias py="python"
alias n="node"
alias gopj="cd $GOPATH/src/github.com/"
alias rustrepl="evcxr"
alias tf="terraform"
alias d="docker"
alias dc="docker compose"
alias dcrun="docker compose run --rm"
alias spt="spotify_player"
