#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_topmost               off            \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.50           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xff775759     \
    normal_window_border_color   0xff555555     \
    window_border_width          4              \
    window_border_radius         12             \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                off            \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    external_bar                 all:32:0       \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   05             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

# Manage off for all
# yabai -m rule --add app=.* manage=off

# yabai -m rule --add app=Finder manage=off
yabai -m rule --add app=System\ Preferences manage=off
yabai -m rule --add app=Activity\ Monitor manage=off
yabai -m rule --add app=Console manage=off
yabai -m rule --add app=Screen\ Sharing manage=off
yabai -m rule --add app=Preview manage=off
yabai -m rule --add app=Photos manage=off
yabai -m rule --add app=QuickTime\ Player manage=off
yabai -m rule --add app=Messages manage=off
# yabai -m rule --add app=zoom.us manage=off
# yabai -m rule --add app=Word manage=off
# yabai -m rule --add app=Excel manage=off
# yabai -m rule --add app=PowerPoint manage=off
# yabai -m rule --add app=OneNote manage=off
yabai -m rule --add app=Microsoft\ Remote\ Desktop manage=off
yabai -m rule --add app=TablePlus manage=off
yabai -m rule --add app=Transmit manage=off
yabai -m rule --add app=GitHub\ Desktop manage=off
yabai -m rule --add app=Slack manage=off
yabai -m rule --add app=Spotify manage=off
yabai -m rule --add app=Spark manage=off
# yabai -m rule --add app=Brave\ Browser manage=off
# yabai -m rule --add app=Google\ Chrome manage=off
# yabai -m rule --add app=Firefox manage=off
# yabai -m rule --add app=iTerm2 manage=off

echo "yabai configuration loaded.."
