# Packages
$packages = @(
    "AgileBits.1Password"
    "Microsoft.VisualStudio.2019.Community"
    "Google.AndroidStudio"
    "CPUID.CPU-Z"
    "Canonical.Ubuntu.2004"
    "CrystalDewWorld.CrystalDiskInfo"
    "Discord.Discord"
    "Docker.DockerDesktop"
    "Mozilla.Firefox.DeveloperEdition"
    "GitHub.GitHubDesktop"
    "Git.Git"
    "Google.Chrome"
    "Brave.Brave"
    "HandBrake.HandBrake"
    "Logitech.Options"
    "Microsoft.DevHome"
    "Microsoft.Edge"
    "Microsoft.EdgeWebView2Runtime"
    "Microsoft.WindowsTerminal"
    "Mozilla.Thunderbird"
    "Microsoft.OneDrive"
    "Enterbrain.RGSS-RTPStandard"
    "Valve.Steam"
    "Microsoft.Teams"
    "TeraTermProject.teraterm"
    "JetBrains.Toolbox"
    "TablePlus.TablePlus"
    "UnityTechnologies.Unity.2020"
    "UnityTechnologies.UnityHub"
    "VideoLAN.VLC"
    "Nushell.Nushell"
    "SlackTechnologies.Slack"
    "WinSCP.WinSCP"
    "Microsoft.VC++2013Redist-x64"
    "Microsoft.VC++2013Redist-x64"
    "Microsoft.WindowsInstallationAssistant"
    "Microsoft.PowerShell"
    "Microsoft.WingetCreate"
    "Logitech.LGS"
    "Microsoft.VC++2010Redist-x64"
    "BlenderFoundation.Blender"
    "Microsoft.VC++2015-2019Redist-x64"
    "Microsoft.AzureCLI"
    "Microsoft.VC++2012Redist-x86"
    "Elgato.4KCaptureUtility"
    "Microsoft.dotnetRuntime.5-x64"
    "Elgato.StreamDeck"
    "Microsoft.VC++2008Redist-x64"
    "Google.Drive"
    "Google.ChromeRemoteDesktop"
    "Microsoft.dotnet"
    "Elgato.GameCapture.HD"
    "Microsoft.Teams"
    "Mojang.MinecraftLauncher"
    "Amazon.AWSCLI"
    "Microsoft.PowerToys"
    "TechPowerUp.GPU-Z"
    "Microsoft.VC++2015-2019Redist-x86"
    "Microsoft.dotnet"
    "Microsoft.VC++2008Redist-x86"
    "GitHub.cli"
    "Microsoft.VC++2013Redist-x86"
    "Google.JapaneseIME"
    # "CoreyButler.NVMforWindows"
    "Nvidia.GeForceExperience"
    "Nvidia.PhysX"
    "Microsoft.WindowsPCHealthCheck"
    "EpicGames.EpicGamesLauncher"
    "Microsoft.VisualStudioCode"
    "Microsoft.VC++2010Redist-x86"
    "GoLang.Go"
    "Microsoft.dotnetRuntime.5-x86"
    "Microsoft.VC++2005Redist-x64"
    "Microsoft.dotnetRuntime.3-x86"
    "Microsoft.VC++2012Redist-x64"
    "Microsoft.VC++2013Redist-x86"
    "WinMerge.WinMerge"
    "JanDeDobbeleer.OhMyPosh"
    "Neovim.Neovim"
    "Starship.Starship"
    "Volta.Volta"
    "sharkdp.bat"
    "Zeit.Hyper"
    "Gyan.FFmpeg"
    "MAMP.MAMP"
    "Alacritty.Alacritty"
    "wez.wezterm"
    "tailscale.tailscale"
)

# Install packages
Write-Host ("Installing " + $packages.count + " packages...`r`n")
foreach ($package in $packages)
{
    # winget install $package
}

Write-Host "`r`nInstallation is successfully completed." -ForegroundColor Green


