# Packages
$packages = @(
  "AgileBits.1Password"
  "Microsoft.VisualStudio.2019.Community"
  "CPUID.CPU-Z"
  "CrystalDewWorld.CrystalDiskInfo"
  "Discord.Discord"
  "Docker.DockerDesktop"
  "Mozilla.Firefox.DeveloperEdition"
  "Git.Git"
  "Google.Chrome"
  "Brave.Brave"
  "HandBrake.HandBrake"
  "Logitech.Options"
  "Microsoft.DevHome"
  "Enterbrain.RGSS-RTPStandard"
  "Valve.Steam"
  "JetBrains.Toolbox"
  "TablePlus.TablePlus"
  "UnityTechnologies.UnityHub"
  "VideoLAN.VLC"
  "SlackTechnologies.Slack"
  # "Microsoft.VC++2013Redist-x64"
  # "Microsoft.VC++2013Redist-x64"
  "Microsoft.WindowsInstallationAssistant"
  "Microsoft.WingetCreate"
  "Logitech.LGS"
  # "Microsoft.VC++2010Redist-x64"
  "BlenderFoundation.Blender"
  # "Microsoft.VC++2015-2019Redist-x64"
  "Microsoft.AzureCLI"
  # "Microsoft.VC++2012Redist-x86"
  "Elgato.4KCaptureUtility"
  "Microsoft.dotnetRuntime.5-x64"
  "Elgato.StreamDeck"
  "Streamlabs.Streamlabs"
  # "Microsoft.VC++2008Redist-x64"
  "Google.Drive"
  "Google.ChromeRemoteDesktop"
  "Microsoft.dotnet"
  "Elgato.GameCapture.HD"
  "Mojang.MinecraftLauncher"
  "Amazon.AWSCLI"
  "Microsoft.PowerToys"
  "TechPowerUp.GPU-Z"
  # "Microsoft.VC++2015-2019Redist-x86"
  "Microsoft.dotnet"
  # "Microsoft.VC++2008Redist-x86"
  "GitHub.cli"
  # "Microsoft.VC++2013Redist-x86"
  "Microsoft.WindowsPCHealthCheck"
  "EpicGames.EpicGamesLauncher"
  "Microsoft.VisualStudioCode"
  # "Microsoft.VC++2010Redist-x86"
  "GoLang.Go"
  # "Microsoft.dotnetRuntime.5-x86"
  # "Microsoft.VC++2005Redist-x64"
  # "Microsoft.dotnetRuntime.3-x86"
  # "Microsoft.VC++2012Redist-x64"
  # "Microsoft.VC++2013Redist-x86"
  "WinMerge.WinMerge"
  "Neovim.Neovim"
  "Starship.Starship"
  "Volta.Volta"
  "sharkdp.bat"
  "Zeit.Hyper"
  "MAMP.MAMP"
  "Alacritty.Alacritty"
  "wez.wezterm"
  "tailscale.tailscale"
  "Cloudflare.Warp"
  "Cloudflare.cloudflared"
)

# Install packages
Write-Host ("Installing " + $packages.count + " packages...`r`n")
foreach ($package in $packages) {
  winget install $package
}

Write-Host "`r`nInstallation is successfully completed." -ForegroundColor Green
