-- https://github.com/folke/noice.nvim
--
-- icons:
-- https://www.nerdfonts.com/cheat-sheet
--
return {
  -- "folke/noice.nvim",
  -- dependencies = {
  --   { "MunifTanjim/nui.nvim" },
  --   { "rcarriga/nvim-notify" }, -- for notifications
  -- },
}

-- noice.setup {
--   cmdline = {
--     format = {
--       cmdline = {
--         pattern = "^:", icon = "", lang = "vim"
--       },
--       search_down = {
--         kind = "search", pattern = "^/", icon = " ", lang = "regex"
--       },
--       search_up = {
--         kind = "search", pattern = "^%?", icon = " ", lang = "regex"
--       },
--       filter = {
--         pattern = "^:%s*!", icon = "$", lang = "bash"
--       },
--       lua = {
--         pattern = { "^:%s*lua%s+", "^:%s*lua%s*=%s*", "^:%s*=%s*" },
--         icon = "",
--         lang = "lua"
--       },
--       help = {
--         pattern = "^:%s*he?l?p?%s+", icon = "󰋗"
--       },
--     }
--   },
--   messages = {
--     enabled = false,
--     view = "notify",
--     view_error = "notify",
--     view_warn = "notify",
--     view_history = "messages",
--     view_search = "mini",
--   },
--   routes = {
--     {
--       view = "mini",
--       filter = {
--         find = "written",
--       }
--     }
--   },
--   lsp = {
--     signature = {
--       enabled = false,
--     },
--   },
--   health = {
--     checker = true,
--   }
-- }
