#!/bin/bash

# List array of installed packages
packages=(
    "curl"
    "tree"
    "zsh"
    "fish"
    "neovim"
    "bat"
    # "powershell"
)

cat <<EOF
=============================================
  apt Installer
=============================================
EOF

# Update package list
printf "Updating package list..."
sudo apt update -y

# Install packages
for package in "${packages[@]}"; do
  if [ "$package" != "" ]; then
    printf "Installing $package..."
    sudo apt install -y $package
  fi

  # Rename for bat
  if [ "$package" == "bat" ]; then
    mkdir -p ~/.local/bin
    ln -s /usr/bin/batcat /usr/local/bin/bat
  fi
done

