#!/bin/bash

packages=(
    "git"
    "curl"
    "wget"
    "apt-transport-https"
    "software-properties-common"
    "tree"
    "zsh"
    "fish"
    "neovim"
    "bat"
    "neofetch"
    "luajit"
    # "powershell"
)

repositories=(
    "ppa:neovim-ppa/stable"
)

# software-properties-common
sudo apt update
sudo apt install software-properties-common -y

# add-apt-repository
for repository in "${repositories[@]}"; do
  if [ "$repository" != "" ]; then
    printf "Adding APT Repository: $repository...\n"
    sudo add-apt-repository $repository -y
  fi
done

# GPG Keys

# Update package list
printf "Updating package list...\n"
sudo apt update -y

# Install packages
for package in "${packages[@]}"; do
  if [ "$package" != "" ]; then
    printf "Installing $package...\n"
    sudo apt install -y $package
  fi

  # Rename for bat
  if [ "$package" == "bat" ]; then
    mkdir -p ~/.local/bin
    ln -s /usr/bin/batcat /usr/local/bin/bat
  fi
done

