#!/bin/bash

packages=(
    "git"
    "curl"
    "wget"
    "apt-transport-https"
    "software-properties-common"
    "tree"
    "zsh"
    "fish"
    "neovim"
    "bat"
    "neofetch"
    # "powershell"
)

# GPG Keys

# Update package list
printf "Updating package list...\n"
sudo apt update -y

# Install packages
for package in "${packages[@]}"; do
  if [ "$package" != "" ]; then
    printf "Installing $package...\n"
    sudo apt install -y $package
  fi

  # Rename for bat
  if [ "$package" == "bat" ]; then
    mkdir -p ~/.local/bin
    ln -s /usr/bin/batcat /usr/local/bin/bat
  fi
done

