# Variables
export XDG_CONFIG_HOME="$HOME/.config"
export SSH_AUTH_SOCK="$HOME/.1password/agent.sock"
export GOPATH="$HOME/go"
export MODULAR_HOME="$HOME/.modular"
export COMPOSER_HOME="$XDG_CONFIG_HOME/composer"
export BUN_INSTALL="$HOME/.bun"
export JAVA_HOME="/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home"
# export JAVA_HOME="/opt/homebrew/opt/openjdk@23/libexec/openjdk.jdk/Contents/Home"
# export JAVA_HOME="/opt/homebrew/opt/openjdk@22/libexec/openjdk.jdk/Contents/Home"
# export JAVA_HOME="/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home"
