export BASH_SILENCE_DEPRECATION_WARNING=1
export CLICOLOR=true
export TERM="xterm-256color"
export EDITOR="nvim"
export GH_URL="https://github.com"
export AWS_PROFILE="default"
export AWS_DEFAULT_REGION="ap-northeast-1"
export DARWIN_USER=$(whoami)
export DARWIN_HOST=$(hostname -s)
