{
  pkgs,
  lib,
  config,
  userProfile,
  ...
}:
let
  dotenvEnvironments = [
    "local"
    "development"
    "staging"
    "production"
  ];

  dotenvFiles = lib.concatMap (env: [
    ".env.${env}"
    ".dev.vars.${env}"
  ]) dotenvEnvironments;

  # Per-client `includeIf` blocks are generated at *activation* time rather than
  # at evaluation time. Reading secrets.json during evaluation forced every
  # command to run with `--impure`, and under pure evaluation it silently
  # produced a different derivation (no client overrides) instead of failing.
  #
  # git ignores an include path that does not exist, so a machine without
  # secrets.json simply ends up with no client overrides.
  secretsPath = "${config.home.homeDirectory}/dotfiles/secrets.json";
  clientsIncludePath = "${config.home.homeDirectory}/.config/git.custom/clients.gitconfig";

  gitClientsInclude = pkgs.writeShellApplication {
    name = "git-clients-include";
    runtimeInputs = [ pkgs.jq ];
    text = ''
      secrets="''${1:?usage: git-clients-include <secrets.json> <out.gitconfig>}"
      out="''${2:?usage: git-clients-include <secrets.json> <out.gitconfig>}"

      mkdir -p "$(dirname "$out")"
      tmp="$(mktemp "$out.XXXXXX")"
      trap 'rm -f "$tmp"' EXIT

      {
        echo "# Generated from $secrets by home-manager activation. Do not edit."
        if [ -r "$secrets" ]; then
          jq -r '
            (.gitClients // [])[]
            | "[includeIf \"gitdir:~/repos/\(.dir)/\"]\n\tpath = ~/.config/git.custom/\(.configFile)"
          ' "$secrets"
        fi
      } >"$tmp"

      mv "$tmp" "$out"
    '';
  };

  ignoreFiles = [
    # macOS
    ".DS_Store"
    ".AppleDouble"
    ".LSOverride"
    ".DocumentRevisions-V100"
    ".fseventsd"
    ".Spotlight-V100"
    ".TemporaryItems"
    ".Trashes"
    ".VolumeIcon.icns"
    ".com.apple.timemachine.donotpresent"

    # Windows
    "Thumbs.db"
    "desktop.ini"

    # Editors / IDEs
    ".clj-kondo/.cache/"
    ".lsp/.cache/"
    ".idea/"
    ".vscode/"

    # Node.js
    "**/node_modules"
    "npm-debug.log*"
    "yarn-debug.log*"
    "yarn-error.log*"
    "lerna-debug.log*"
    ".pnpm-debug.log*"
    "pids"
    "*.pid"
    "*.seed"
    "*.pid.lock"
    "*.tsbuildinfo"
    ".yarn/cache"
    ".yarn/unplugged"
    ".yarn/build-state.yml"
    ".yarn/install-state.gz"
    ".pnp.*"

    # Nix / Devenv
    ".direnv"
    ".devenv*"
    "devenv.local.nix"
    "devenv.local.yaml"

    # Misc
    ".ignore/"
    ".playwright-mcp/"
    "**/.claude/settings.local.json"
    "**/.claude/worktrees/"
    "AGENTS.local.md"
    "mise.local.toml"
    ".pre-commit-config.yaml"
  ]
  ++ dotenvFiles;
in
{
  programs.git = {
    enable = true;

    # Identity, signing, and OS-specific GPG stay in Nix (userProfile-derived and
    # host-varying). The static config (aliases, diff, color, ...) lives in a repo
    # file included directly by git, so it is editable in place without a rebuild.
    # See #70.
    settings = {
      user = {
        name = userProfile.name;
        email = userProfile.email;
        username = userProfile.username;
        signingkey = userProfile.signingKey;
      };

      github = {
        user = userProfile.username;
      };

      # OS-specific GPG configuration for 1Password SSH signing
      gpg = {
        format = "ssh";
      }
      // (lib.optionalAttrs pkgs.stdenv.isDarwin {
        ssh.program = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign";
      })
      // (lib.optionalAttrs pkgs.stdenv.isLinux {
        ssh.program = "/mnt/c/Program Files/1Password/app/8/op-ssh-sign-wsl";
      });
    };

    includes = [
      { path = "${config.home.homeDirectory}/dotfiles/config/git/config"; }
      # Generated by the activation script below; listed last so client
      # overrides win over the shared config.
      { path = clientsIncludePath; }
    ];

    ignores = ignoreFiles;
  };

  home.activation.gitClientsInclude = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    run ${gitClientsInclude}/bin/git-clients-include ${lib.escapeShellArg secretsPath} ${lib.escapeShellArg clientsIncludePath}
  '';

  programs.gh = {
    enable = true;
    gitCredentialHelper = {
      enable = true;
      hosts = [
        "https://github.com"
        "https://gist.github.com"
      ];
    };
    extensions = with pkgs; [
      gh-markdown-preview
    ];
    settings = {
      aliases = {
        as = "auth status";
        co = "pr checkout";
        pv = "pr view";
        sw = "auth switch";
      };
      git_protocol = "https";
    };
  };

  programs.jujutsu = {
    enable = true;
    settings = {
      user = {
        email = userProfile.email;
        name = userProfile.name;
      };
    };
  };
}
