"$schema" = 'https://starship.rs/config-schema.json'

scan_timeout = 30
command_timeout = 500
add_newline = true
follow_symlinks = true

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red)'

[line_break]
disabled = false

[docker_context]
disabled = true

[gcloud]
disabled = true

[memory_usage]
disabled = true
threshold = -1
style = 'bold dimmed green'

[sudo]
disabled = false
