format = """
$os\
$localip\
[](bg:v_secondary fg:v_primary)\
$directory\
[ ](bg:v_base fg:v_secondary)\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$php\
[](fg:v_base)\
\n$character"""

palette = "tokyo-night"

[palettes.tokyo-night]
git-green = '#6CA53A'
# Variants
v_base = '#202334'
v_primary = '#83A1F1'
v_secondary = '#3D425F'
v_tertiary = '#3D4A6D'
# Text colors
t_base = '#769ff0'
t_primary = '#1E202E'
t_secondary = '#7892DA'
t_tertiary = '#D9DBE3'

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[os]
disabled = false
format = '[  $symbol  ](bg:v_primary fg:t_primary)'

[os.symbols]
Arch = ""
CentOS = ""
Debian = ""
Fedora = ""
FreeBSD = ""
Gentoo = ""
Linux = ""
Macos = ""
Mint = ""
NixOS = ""
Ubuntu = ""
Unknown = ""
Windows = ""

[localip]
ssh_only = true
format = '[$localipv4  ](bg:v_primary fg:t_primary bold)'
disabled = false

[directory]
format = "[  $path ](bg:v_secondary fg:t_secondary)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "

[git_branch]
symbol = ""
format = '[[$symbol $branch ](fg:git-green bg:v_base bold)](bg:v_base)'

[git_status]
format = '[[($all_status$ahead_behind )](fg:t_base bg:v_base)](bg:v_base$style)'

[nodejs]
symbol = ""
style = "bg:v_base"
format = '[[ $symbol ($version) ](fg:t_base bg:v_base)]($style)'

[rust]
symbol = ""
style = "bg:v_base"
format = '[[ $symbol ($version) ](fg:t_base bg:v_base)]($style)'

[golang]
symbol = ""
style = "bg:v_base"
format = '[[ $symbol ($version) ](fg:t_base bg:v_base)]($style)'

[php]
symbol = ""
style = "bg:v_base"
format = '[[ $symbol ($version) ](fg:t_base bg:v_base)]($style)'
