format = """
[    ](bg:#444444 fg:#ffffff)\
$localip\
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$php\
[](fg:#444444 bg:#1d2230)\
$status\
[ ](fg:#1d2230)\
"""

[localip]
ssh_only = true
format = '[ $localipv4 ](bg:#a3aed2 fg:#090c0c bold)'
disabled = false

[directory]
style = "fg:#4692CB bg:#444444 bold"
format = "[  $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#444444"
format = '[[ $symbol $branch ](fg:#6CA53A bg:#444444 bold)]($style)'

[git_status]
style = "bg:#444444"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#444444)]($style)'

[nodejs]
symbol = ""
style = "bg:#444444"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#444444)]($style)'

[rust]
symbol = ""
style = "bg:#444444"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#444444)]($style)'

[golang]
symbol = ""
style = "bg:#444444"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#444444)]($style)'

[php]
symbol = ""
style = "bg:#444444"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#444444)]($style)'

[status]
format = '[ $symbol ]($style)'
style = "bg:#1d2230 fg:#769ff0 bold"
symbol = ""
success_symbol = ""
not_executable_symbol = ""
not_found_symbol = ""
sigint_symbol = ""
signal_symbol = ""
disabled = false
