"$schema" = 'https://starship.rs/config-schema.json'

scan_timeout = 30
command_timeout = 500
add_newline = true
follow_symlinks = true

[line_break]
disabled = false

[aws]
disabled = true

[docker_context]
disabled = true

[gcloud]
disabled = true

[memory_usage]
disabled = true
threshold = -1
style = 'bold dimmed green'

[sudo]
disabled = false

[vagrant]
disabled = true
