format = """
[    ](bg:#333333 fg:#ffffff)\
$localip\
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$php\
[](fg:#333333 bg:#1d2230)\
$status\
[ ](fg:#1d2230)\
\n$character
"""

[localip]
ssh_only = true
format = '[$localipv4  ](bg:#333333 fg:#eeeeee bold)'
disabled = false

[directory]
style = "fg:#46A3FF bg:#333333 bold"
format = "[  $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#333333"
format = '[[$symbol $branch ](fg:#6CA53A bg:#333333 bold)]($style)'

[git_status]
style = "bg:#333333"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#333333)]($style)'

[status]
format = '[ $symbol ]($style)'
style = "bg:#1d2230 fg:#769ff0 bold"
symbol = ""
success_symbol = ""
not_executable_symbol = ""
not_found_symbol = ""
sigint_symbol = ""
signal_symbol = ""
disabled = false

[nodejs]
symbol = ""
style = "bg:#333333"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#333333)]($style)'

[rust]
symbol = ""
style = "bg:#333333"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#333333)]($style)'

[golang]
symbol = ""
style = "bg:#333333"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#333333)]($style)'

[php]
symbol = ""
style = "bg:#333333"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#333333)]($style)'

