format = """
$os\
$localip\
[](bg:v_secondary fg:v_primary)\
$directory\
[ ](bg:v_base fg:v_secondary)\
$git_branch\
$git_status\
[](fg:v_base)\
\n$character"""

palette = "tokyo-night"

[palettes.tokyo-night]
git-green = '#6CA53A'
v_base = '#202334'
v_primary = '#83A1F1'
v_secondary = '#3D425F'
v_tertiary = '#3D4A6D'
t_base = '#769ff0'
t_primary = '#1E202E'
t_secondary = '#7892DA'
t_tertiary = '#D9DBE3'

[os]
disabled = false
format = '[  $symbol  ](bg:v_primary fg:t_primary)'

[os.symbols]
Arch = ""
CentOS = ""
Debian = ""
Fedora = ""
FreeBSD = ""
Gentoo = ""
Linux = ""
Macos = ""
Mint = ""
NixOS = ""
Ubuntu = ""
Unknown = ""
Windows = ""

[localip]
ssh_only = true
format = '[$localipv4  ](bg:v_primary fg:t_primary bold)'
disabled = false

[directory]
format = "[  $path ](bg:v_secondary fg:t_secondary)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "

[git_branch]
symbol = ""
format = '[[$symbol $branch ](fg:git-green bg:v_base bold)](bg:v_base)'

[git_status]
format = '[[($all_status$ahead_behind )](fg:t_base bg:v_base)](bg:v_base$style)'

