# Colors based on tokyo-night
#
# Background:
# - Base: #202334
# - Primary: #83A1F1
# - Secondary: #3D425F
#
# Foreground:
# - Base: #ffffff
# - Primary: #1E202E
# - Secondary: #7892DA

format = """
$os\
$localip\
[](bg:#3D425F fg:#83A1F1)\
$directory\
[ ](bg:#202334 fg:#3D425F)\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$php\
[ ](fg:#1d2230)\
\n$character"""

[os]
disabled = false
format = '[  $symbol  ]($style)'
style = "bg:#83A1F1 fg:#1E202E"
[os.symbols]
Arch = ""
CentOS = ""
Debian = ""
Fedora = ""
FreeBSD = ""
Gentoo = ""
Linux = ""
Macos = ""
Mint = ""
NixOS = ""
Ubuntu = ""
Unknown = ""
Windows = ""

[localip]
ssh_only = true
format = '[$localipv4  ](bg:#83A1F1 fg:#1E202E bold)'
disabled = false

[directory]
style = "bg:#3D425F fg:#7892DA bold"
format = "[  $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#202334"
format = '[[$symbol $branch ](fg:#6CA53A bg:#202334 bold)]($style)'

[git_status]
style = "bg:#202334"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#202334)]($style)'

[nodejs]
symbol = ""
style = "bg:#202334"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#202334)]($style)'

[rust]
symbol = ""
style = "bg:#202334"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#202334)]($style)'

[golang]
symbol = ""
style = "bg:#202334"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#202334)]($style)'

[php]
symbol = ""
style = "bg:#202334"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#202334)]($style)'

