#
# Alacritty Configuration
#
import = [
  "~/.config/alacritty/color.toml",
  "~/.config/alacritty/font.toml",
  "~/.config/alacritty/window.toml",
]

live_config_reload = true

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
GITHUB_USERNAME = "siraken"
TERM = "xterm-256color"

[mouse]
hide_when_typing = false

[scrolling]
history = 10000

[shell]
program = "/opt/homebrew/bin/fish"

[keyboard]
bindings = []

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
renderer = "None"
print_events = false
highlight_damage = false
prefer_egl = false
