#!/bin/bash

# List array of installed packages
packages=(
)
sudo apt install tree fish curl -y

cat <<EOF
=============================================
  apt Installer
=============================================
EOF

# Update package list
echo "Updating package list..."
sudo apt update -y

# Install packages
for package in "${packages[@]}"; do
  if [ "$package" != "" ]; then
    echo "Installing $package..."
    sudo apt install -y $package
  fi
done

