#!/bin/bash

# List array of installed packages
packages=(
  "bat"
  "exa"
  "fish"
  "gh"
  "git"
  "golang"
  "neovim"
  "nodejs-lts"
  "tmux"
  "tree"
  "vim"
  "wget"
  "yarn"
  "zsh-completions"
  "zsh"
)

cat <<EOF
=============================================
 termux-setup
=============================================
EOF

# Update package list
echo "Updating package list..."
pkg update -y

# Install packages
for package in "${packages[@]}"; do
  if [ "$package" != "" ]; then
    echo "Installing $package..."
    pkg install -y $package
  fi
done

