#!/bin/bash

# List array of packages
packages=(
    "spt"
)

cat <<EOF
=============================================
 snap Installer
=============================================
EOF

# Update package list
echo "Updating package list..."
snap refresh

# Install packages
for package in "${packages[@]}"; do
  if [ "$package" != "" ]; then
    echo "Installing $package..."
    snap install $package
  fi
done

