#!/bin/bash

# ==============================

# ==============================
sudo apt update
sudo apt upgrade

# ==============================

# ==============================
sudo apt install tree fish curl

# ==============================

# ==============================
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
