name: Flake Updater
on:
  schedule:
    # Every day at 06:00 and 18:00 JST (21:00 and 09:00 UTC)
    - cron: "0 9,21 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update:
    name: Update Flake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - uses: DeterminateSystems/determinate-nix-action@131015bad844610e5e6300f8a143bf625d3e74f4 # v3.17.0
      - name: Update flake.lock
        run: nix flake update --commit-lock-file
      - name: Run nix flake check
        run: nix flake check --impure
      - name: Push changes
        run: git push
