[tools]
usage = "latest"
bun = "latest"
deno = "latest"
node = "latest"
erlang = "latest"
python = "3"
ruby = "latest"
zig = "latest"
ghq = "latest"
uv = "latest"
go = "latest"

[settings]
idiomatic_version_file_enable_tools = []

[settings.npm]
bun = true

[settings.status]
missing_tools = "if_other_versions_installed"
show_env = false
show_tools = false
